export {default as Banner} from "./Banner"
export {default as Welcome} from "./Welcome"
export {default as Teams} from "./Teams"
export {default as Footer} from "./Footer"
export {default as Purchase} from "./Purchase"